stages:
  - test
  - deploy

test:
  stage: test
  image: php:8.1
  services:
    - mysql:8.0
  variables:
    DB_HOST: mysql
    DB_DATABASE: local
    DB_USERNAME: root
    DB_PASSWORD: rootpassword
  script:
    - apt-get update && apt-get install -y zip unzip git
    - curl -sS https://getcomposer.org/installer | php
    - mv composer.phar /usr/local/bin/composer
    - cd app/ReviewPortal  # Change to the directory where composer.json is located
    - composer install
    - php artisan migrate --force
    - php artisan test

deploy:
  stage: deploy
  script:
    - echo "Deploying to production"
    # Add additional deploy steps here as needed
