stages:
  - test
  - deploy

test:
  stage: test
  image: php:8.2
  services:
    - mysql:8.0
  variables:
    DB_HOST: mysql
    DB_DATABASE: testing
    DB_USERNAME: root
    DB_PASSWORD: rootpassword
  script:
    # Install necessary dependencies for Laravel and MySQL support
    - apt-get update && apt-get install -y zip unzip git libmariadb-dev

    # Install Composer
    - curl -sS https://getcomposer.org/installer | php
    - mv composer.phar /usr/local/bin/composer

    # Navigate to Laravel project directory
    - cd app/ReviewPortal

    # Install PHP dependencies
    - composer install --no-interaction --prefer-dist --optimize-autoloader

    # Copy environment files for testing
    - cp .env.example .env
    - cp .env .env.testing

    # Generate app key and run migrations
    - php artisan key:generate --env=testing
    - php artisan config:clear
    - php artisan migrate --force --env=testing

    # Run the tests
    - php artisan test --env=testing

deploy:
  stage: deploy
  script:
    - echo "Deploying the application..."
    # Add your deployment commands here
