stages:
  - setup
  - test

variables:
  APP_ENV: testing
  DB_CONNECTION: mysql

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - app/ReviewPortal/vendor/

setup:
  stage: setup
  image: php:8.2
  script:
    # Install system dependencies (fixed formatting)
    - apt-get update && apt-get install -y unzip libzip-dev libpng-dev libonig-dev libxml2-dev
      
    # Install PHP extensions
    - docker-php-ext-install pdo_mysql mbstring zip exif pcntl bcmath gd

    # Install Composer
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

    # Set up Laravel
    - cd app/ReviewPortal
    - composer install --no-interaction --prefer-dist --optimize-autoloader
    - cp .env.example .env
    - php artisan key:generate

  artifacts:
    paths:
      - app/ReviewPortal/vendor/
    expire_in: 1 week

test:
  stage: test
  image: php:8.2
  services:
    - name: mysql:8.0
      alias: mysql
      command: ["--default-authentication-plugin=mysql_native_password"]
  variables:
    DB_HOST: mysql
    DB_PORT: 3306
    DB_DATABASE: mysql_db
    DB_USERNAME: root
    DB_PASSWORD: rootpassword
  script:
    - cd app/ReviewPortal
    
    # Wait for MySQL to be ready
    - for i in {1..10}; do
        mysql -h mysql -u root -prootpassword -e "SELECT 1" && break || sleep 5;
      done

    # Run database migrations and tests
    - php artisan migrate:fresh --force
    - php artisan test

  artifacts:
    when: always
    paths:
      - app/ReviewPortal/storage/logs/
    reports:
      junit: app/ReviewPortal/tests/Unit/junit.xml