version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./app/ReviewPortal:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini  # Correct path
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Set the root password
      MYSQL_DATABASE: local
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab_runner
    volumes:
      - /Users/asadpirzada/gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

volumes:
  db_data:
