stages:
  - test
  - deploy

test:
  stage: test
  image: php:8.2
  services:
    - mysql:8.0
  variables:
    DB_HOST: mysql
    DB_DATABASE: testing
    DB_USERNAME: root
    DB_PASSWORD: rootpassword
  script:
    - apt-get update && apt-get install -y zip unzip git
    - curl -sS https://getcomposer.org/installer | php
    - mv composer.phar /usr/local/bin/composer
    - cd app/ReviewPortal
    # Install Composer dependencies
    - composer install --no-interaction --prefer-dist --optimize-autoloader

    # Ensure the .env file exists or copy it
    - if [ ! -f .env ]; then cp .env.example .env; fi
    - cp .env .env.testing

    # Generate the application key, clear config cache, and run migrations and tests
    - php artisan key:generate --env=testing
    - php artisan config:clear
    - until mysql -h "$DB_HOST" -u "$DB_USERNAME" -p"$DB_PASSWORD" -e 'select 1'; do echo "Waiting for MySQL..."; sleep 5; done
    - php artisan migrate --force --env=testing
    - php artisan test --env=testing
